name: Auto Version Bump with GitHub Links

on:
  push:
    paths:
      - 'tag.md'
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get current version
      id: version
      run: |
        # Extract the current two-part version (e.g., 1.0) from the tag.md file
        current_version=$(grep '^# Version' tag.md | cut -d ' ' -f 3)
        echo "Current version: $current_version"
        echo "current_version=$current_version" >> $GITHUB_ENV
      
    - name: Bump version
      id: bump
      run: |
        # Bump the minor version (second number in two-part versioning)
        version=${{ env.current_version }}
        new_version=$(echo $version | awk -F. '{printf("%d.%d\n", $1, $2+1)}')  # Increment only the minor part
        echo "New version: $new_version"
        echo "new_version=$new_version" >> $GITHUB_ENV
      
    - name: Update tag.md with new version
      run: |
        new_version=${{ env.new_version }}
        # Update the version in tag.md
        sed -i "s/^# Version.*/# Version $new_version/" tag.md

    - name: Commit and push changes
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add tag.md
        git commit -m "Bump version to ${{ env.new_version }}" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Get latest commit hash
      id: commit_hash
      run: |
        # Get the latest commit hash for linking purposes
        commit_hash=$(git rev-parse HEAD)
        echo "commit_hash=$commit_hash" >> $GITHUB_ENV
      
    - name: Update versioning log with GitHub commit link
      run: |
        new_version=${{ env.new_version }}
        commit_hash=${{ env.commit_hash }}
        date=$(date +"%Y-%m-%d")
        # Append the new version entry to VERSIONING.md with a link to the commit
        echo "| [$new_version](https://github.com/${{ github.repository }}/blob/${commit_hash}/tag.md) | $date | Changes made | $(git config user.name) |" >> VERSIONING.md

    - name: Commit and push VERSIONING.md
      run: |
        git add VERSIONING.md
        git commit -m "Update versioning log for ${{ env.new_version }}" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
