name: Auto Version Bump with PDF Snapshot

on:
  push:
    paths:
      - 'tag.md'
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install wkhtmltopdf
      run: |
        sudo apt-get update
        sudo apt-get install -y wkhtmltopdf

    - name: Get current version
      id: version
      run: |
        current_version=$(grep '^# Version' tag.md | cut -d ' ' -f 3)
        echo "current_version=$current_version" >> $GITHUB_ENV
      
    - name: Bump version
      id: bump
      run: |
        version=${{ env.current_version }}
        new_version=$(echo $version | awk -F. '{printf("%d.%d\n", $1, $2+1)}')
        echo "new_version=$new_version" >> $GITHUB_ENV

    - name: Update tag.md with new version
      run: |
        new_version=${{ env.new_version }}
        sed -i "s/^# Version.*/# Version $new_version/" tag.md

    - name: Commit and push changes
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add tag.md
        git commit -m "Bump version to ${{ env.new_version }}" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Get latest commit hash
      id: commit_hash
      run: |
        commit_hash=$(git rev-parse HEAD)
        echo "commit_hash=$commit_hash" >> $GITHUB_ENV

    - name: Generate PDF from tag.md using wkhtmltopdf
      run: |
        new_version=${{ env.new_version }}
        wkhtmltopdf tag.md "tag_${new_version}.pdf"

    - name: Commit and push the PDF
      run: |
        git add "tag_${{ env.new_version }}.pdf"
        git commit -m "Add PDF for version ${{ env.new_version }}"
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Update versioning log with PDF link
      run: |
        new_version=${{ env.new_version }}
        echo "| [$new_version](https://github.com/${{ github.repository }}/raw/main/tag_${new_version}.pdf) | $(date +"%Y-%m-%d") | Changes made | $(git config user.name) |" >> VERSIONING.md

    - name: Commit and push VERSIONING.md
      run: |
        git add VERSIONING.md
        git commit -m "Update versioning log for ${{ env.new_version }}"
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
