name: Auto Version Bump with Link to tag.md

on:
  push:
    paths:
      - 'tag.md'
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get current version
      id: version
      run: |
        current_version=$(grep '^# Version' tag.md | cut -d ' ' -f 3)
        echo "current_version=$current_version" >> $GITHUB_ENV
      
    - name: Bump version
      id: bump
      run: |
        version=${{ env.current_version }}
        new_version=$(echo $version | awk -F. '{printf("%d.%d\n", $1, $2+1)}')
        echo "new_version=$new_version" >> $GITHUB_ENV

    - name: Update tag.md with new version
      run: |
        new_version=${{ env.new_version }}
        sed -i "s/^# Version.*/# Version $new_version/" tag.md

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add tag.md
        git commit -m "Bump version to ${{ env.new_version }}" || echo "No changes to commit"
        git push

    - name: Get latest commit hash
      id: commit_hash
      run: |
        commit_hash=$(git rev-parse HEAD)
        echo "commit_hash=$commit_hash" >> $GITHUB_ENV

    - name: Update versioning log with tag.md link
      run: |
        new_version=${{ env.new_version }}
        commit_hash=${{ env.commit_hash }}
        echo "| [$new_version](https://github.com/${{ github.repository }}/blob/${commit_hash}/tag.md) | $(date +"%Y-%m-%d") | Changes made | ${{ github.actor }} |" >> .tag/VERSIONING.md

    - name: Commit and push VERSIONING.md
      run: |
        git add ".tag/VERSIONING.md"  # Ensure to add the VERSIONING.md in the .tag directory
        git commit -m "Update versioning log for ${{ env.new_version }}"
        git push
